### ISSUE TITLE
Why fetch the templates separately?

### ISSUE THREAD

**Issue by thorn0** [lenakmeth/Wikinflection#1]
The templates are included in the dump. Why is `pull_templates.py` needed?

**Comment by thorn0** [comment]
Never mind. Found the answer in your paper.

**Comment by lenakmeth** [comment]
It is far from ideal, unfortunately. The templates that are explicitly written in their own page are available in the dump, but these are very rare occasions (and a bad practice). The modules that generate templates are included in the dump, and they are just XML pages with nested Lua code. It's fairly easy to extract this code, but hard to run unsupervised (you'd have to check that all arguments are met).
